{% set name = "SINA" %}
{% set version = "1.3.1-a1" %}
{% set sha256 = "0986de6e4223320f7a8ae20b1dfedd9204d5c97a63156a50eb6a44f78de6fa2e" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace('-','') }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/epruesse/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  nunmber: 0
  skip: True  # [win]

requirements:
  build:
    - arb-bio
    - boost
  run:
    - arb-bio
    - boost

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]
    - sina --help

about:
  home: https://github.com/epruesse/SINA
  license: GPLv3
  license_family: GPL
  license_file: LICENSE
  summary: SINA add-to-reference sequence alignment tool